// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('Home', function () {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function () {
    driver = await new Builder().forBrowser('safari').build()
    vars = {}
  })
  afterEach(async function () {
    await driver.quit();
  })
  it('Home', async function () {
    await driver.get("http://www.sjsl.org/clubsite/?p=19926")
    // await driver.sleep(20000);

    await driver.manage().window().setRect(1680, 1027)
    assert(await driver.getTitle() == "Home")
    //await driver.findElement(By.css("#top-nav > li:nth-child(1) > a")).click()
    //await driver.findElement(By.linkText("Invoices")).click()
  })
})
