theme: jekyll-theme-minimal
logo: logo.png
title: South Jersey Soccer League
description: SJSL has over 70 affiliated member clubs across the southern half of New Jersey, from Northern Burlington to Cape May, comprising more than 500 boys travel teams from U-8 through U19.
